Centos hardening
verygood-ops/verygood.hardening pull request #4
Opened 2016-12-09 10:09 UTC by sergey-korolev

resolves #3

2016-12-09 11:48 UTC, akhon requested changes

2016-12-09 11:48 UTC, akhon commented on tasks/main.yml
> +  lineinfile: dest=/etc/sudoers regexp="^Defaults.*requiretty" state=absent
@sergey-korolev let's tight up regexp to not have `.*`, we can have only spaces and tabs there

2016-12-09 11:59 UTC, sergey-korolev commented on tasks/main.yml
> +  lineinfile: dest=/etc/sudoers regexp="^Defaults.*requiretty" state=absent
@akhon fixed

2016-12-09 20:20 UTC, akhon commented
@mahmoudimus pls take a look!

2017-01-09 08:34 UTC, sergey-korolev commented
@mahmoudimus Hi. Did you review this PR? Have you any comments with it? Thanks.

2017-01-23 07:51 UTC, akhon commented
@mjallday @mahmoudimus pls review

2017-01-24 19:43 UTC, mjallday approved these changes
👍

2017-01-24 19:44 UTC, merged